export const DEFAULT_CATEGORIES = [
  {
    slug: "jeans",
    name: "Jeans",
    blurb: "Straight, tapered and bootcut, measured flat.",
    measurements: ["Waist", "Inseam", "Rise", "Leg opening"],
    order: 0,
    active: true,
  },
  {
    slug: "pants",
    name: "Pants",
    blurb: "Work pants, chinos and everything between.",
    measurements: ["Waist", "Inseam", "Rise", "Leg opening"],
    order: 1,
    active: true,
  },
  {
    slug: "shirts",
    name: "Shirts",
    blurb: "Oxfords, flannels and tees.",
    measurements: ["Pit to pit", "Length", "Shoulder", "Sleeve"],
    order: 2,
    active: true,
  },
  {
    slug: "jackets",
    name: "Jackets",
    blurb: "Chore coats, truckers and heavy outerwear.",
    measurements: ["Pit to pit", "Length", "Shoulder", "Sleeve"],
    order: 3,
    active: true,
  },
  {
    slug: "shoes",
    name: "Shoes",
    blurb: "Leather, canvas and everything resoled.",
    measurements: ["Insole length"],
    order: 4,
    active: true,
  },
  {
    slug: "belts",
    name: "Belts",
    blurb: "Leather and woven, measured end to end.",
    measurements: ["Total length", "Fits waist", "Width"],
    order: 5,
    active: true,
  },
  {
    slug: "accessories",
    name: "Accessories",
    blurb: "Caps, bags and the rest.",
    measurements: [],
    order: 6,
    active: true,
  },
];
