const W = "/assets/WEBP/";

export const PRODUCTS = [
  {
    slug: "levis-501-straight-w32-l30",
    sku: "GS-0101",
    name: "Levi's 501 Straight",
    tagline: "Honest fade, no stretch",
    brand: "Levi's",
    category: "Jeans",
    sizeSystem: "waist",
    sizeLabel: "W32 L30",
    measurements: {
      Waist: '32"',
      Inseam: '30"',
      Rise: '11"',
      "Leg opening": '7"',
    },
    condition: "Good",
    conditionNotes: "Even fade through the thigh, hem intact, no repairs.",
    priceCents: 480000,
    salePriceCents: 420000,
    costCents: 90000,
    lot: "BALE-04",
    image: W + "64b05489489808ce3e8545b3_T_Shirt_Hero.webp",
    images: [],
    description:
      "Original-fit 501s in a mid indigo that has faded honestly rather than been sanded. Button fly, all rivets present, washed and pressed.",
    details: ["100% cotton denim", "Button fly", "Made in Mexico", "Washed and pressed"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "wrangler-cowboy-cut-w34-l32",
    sku: "GS-0102",
    name: "Wrangler Cowboy Cut",
    tagline: "Stiff, dark, barely worn",
    brand: "Wrangler",
    category: "Jeans",
    sizeSystem: "waist",
    sizeLabel: "W34 L32",
    measurements: {
      Waist: '34"',
      Inseam: '32"',
      Rise: '11.5"',
      "Leg opening": '7.5"',
    },
    condition: "Excellent",
    conditionNotes: null,
    priceCents: 520000,
    salePriceCents: null,
    costCents: 110000,
    lot: "BALE-04",
    image: W + "64b05489489808ce3e8545b3_T_Shirt_Hero.webp",
    images: [],
    description:
      "Rigid denim with almost no wear — the knees and seat are untouched. Runs true to the tag.",
    details: ["Rigid 13 oz denim", "Zip fly", "Five pocket", "Washed and pressed"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "dickies-874-work-pant-w36",
    sku: "GS-0103",
    name: "Dickies 874 Work Pant",
    tagline: "Creased and unbothered",
    brand: "Dickies",
    category: "Pants",
    sizeSystem: "waist",
    sizeLabel: "W36 L30",
    measurements: {
      Waist: '36"',
      Inseam: '30"',
      Rise: '12"',
      "Leg opening": '8"',
    },
    condition: "Good",
    conditionNotes: "Faint mark inside the left cuff, invisible when worn.",
    priceCents: 320000,
    salePriceCents: 280000,
    costCents: 70000,
    lot: "BALE-05",
    image: W + "64b05489489808ce3e8545b3_T_Shirt_Hero.webp",
    images: [],
    description:
      "The permanent-crease work pant in black. Straight through the leg, holds a press, takes a beating.",
    details: ["65% polyester / 35% cotton", "Permanent crease", "Tunnel belt loops"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "carhartt-duck-jacket-l",
    sku: "GS-0201",
    name: "Carhartt Duck Chore Jacket",
    tagline: "Broken in by someone else",
    brand: "Carhartt",
    category: "Jackets",
    sizeSystem: "alpha",
    sizeLabel: "L",
    measurements: {
      "Pit to pit": '24"',
      Length: '28"',
      Shoulder: '20"',
      Sleeve: '25"',
    },
    condition: "Good",
    conditionNotes: "Cuffs softened, one interior pocket seam resewn by us.",
    priceCents: 1450000,
    salePriceCents: 1290000,
    costCents: 340000,
    lot: "BALE-02",
    image: W + "64add86ca2a228b3a73b7657_Sweatshirt_Hero.webp",
    images: [W + "64adce8962f07616f9cf9b0e_Long_Sleeve_Front.webp"],
    description:
      "Firm-hand duck canvas that has already done the hard part of breaking in. Blanket lined, corduroy collar, every snap works.",
    details: ["12 oz cotton duck", "Blanket lined body", "Corduroy collar", "Triple stitched"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "levis-trucker-jacket-m",
    sku: "GS-0202",
    name: "Levi's Trucker Jacket",
    tagline: "Mid wash, sharp collar",
    brand: "Levi's",
    category: "Jackets",
    sizeSystem: "alpha",
    sizeLabel: "M",
    measurements: {
      "Pit to pit": '21"',
      Length: '24"',
      Shoulder: '18"',
      Sleeve: '24.5"',
    },
    condition: "Excellent",
    conditionNotes: null,
    priceCents: 1180000,
    salePriceCents: null,
    costCents: 260000,
    lot: "BALE-02",
    image: W + "64add86ca2a228b3a73b7657_Sweatshirt_Hero.webp",
    images: [],
    description:
      "Clean mid-wash trucker with no fraying at the collar or cuffs. Sits at the waist, layers over a hoodie.",
    details: ["100% cotton denim", "Two chest pockets", "Adjustable waist tabs"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "champion-reverse-weave-hoodie-xl",
    sku: "GS-0203",
    name: "Champion Reverse Weave Hoodie",
    tagline: "Heavy, boxy, holds shape",
    brand: "Champion",
    category: "Jackets",
    sizeSystem: "alpha",
    sizeLabel: "XL",
    measurements: {
      "Pit to pit": '25"',
      Length: '27"',
      Shoulder: '21"',
      Sleeve: '24"',
    },
    condition: "Good",
    conditionNotes: "Slight pilling under the arms.",
    priceCents: 890000,
    salePriceCents: 790000,
    costCents: 180000,
    lot: "BALE-05",
    image: W + "64add86ca2a228b3a73b7657_Sweatshirt_Hero.webp",
    images: [],
    description:
      "The reverse-weave construction that stops the body shrinking upward. Thick fleece, side gussets intact.",
    details: ["82% cotton / 18% polyester", "Reverse weave", "Side gussets", "Kangaroo pocket"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "ralph-lauren-oxford-shirt-m",
    sku: "GS-0301",
    name: "Ralph Lauren Oxford Shirt",
    tagline: "Blue, buttoned, unfussy",
    brand: "Ralph Lauren",
    category: "Shirts",
    sizeSystem: "alpha",
    sizeLabel: "M",
    measurements: {
      "Pit to pit": '22"',
      Length: '30"',
      Shoulder: '18"',
      Sleeve: '24"',
    },
    condition: "Excellent",
    conditionNotes: null,
    priceCents: 420000,
    salePriceCents: null,
    costCents: 80000,
    lot: "BALE-06",
    image: W + "64adce8962f07616f9cf9b0e_Long_Sleeve_Front.webp",
    images: [],
    description:
      "Classic button-down oxford in light blue. Collar has no roll damage, cuffs are clean, all buttons original.",
    details: ["100% cotton oxford", "Button-down collar", "Single chest pocket"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "flannel-overshirt-l",
    sku: "GS-0302",
    name: "Heavy Flannel Overshirt",
    tagline: "Wear it open over everything",
    brand: "Unbranded",
    category: "Shirts",
    sizeSystem: "alpha",
    sizeLabel: "L",
    measurements: {
      "Pit to pit": '23"',
      Length: '31"',
      Shoulder: '19"',
      Sleeve: '25"',
    },
    condition: "Good",
    conditionNotes: "Colour softened from washing, no thinning.",
    priceCents: 380000,
    salePriceCents: 340000,
    costCents: 60000,
    lot: "BALE-06",
    image: W + "64adce8962f07616f9cf9b0e_Long_Sleeve_Front.webp",
    images: [],
    description:
      "Brushed cotton flannel with enough weight to work as a light jacket. Chest pockets, horn-look buttons.",
    details: ["100% brushed cotton", "Two chest pockets", "Washed and pressed"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "plain-white-tee-m",
    sku: "GS-0303",
    name: "Blank Cotton Tee",
    tagline: "The one you actually reach for",
    brand: "Unbranded",
    category: "Shirts",
    sizeSystem: "alpha",
    sizeLabel: "M",
    measurements: {
      "Pit to pit": '20"',
      Length: '28"',
      Shoulder: '17"',
      Sleeve: '8"',
    },
    condition: "Excellent",
    conditionNotes: null,
    priceCents: 140000,
    salePriceCents: null,
    costCents: 25000,
    lot: "BALE-07",
    image: W + "64b05489489808ce3e8545b3_T_Shirt_Hero.webp",
    images: [],
    description:
      "Mid-weight white tee with no graphics, no yellowing at the collar and a straight hem.",
    details: ["100% cotton", "Ribbed collar", "Washed and pressed"],
    status: "sold",
    reservedUntil: null,
    soldAt: "2026-08-30T10:00:00.000Z",
  },
  {
    slug: "leather-derby-shoes-uk9",
    sku: "GS-0401",
    name: "Leather Derby Shoes",
    tagline: "Resoled, not retired",
    brand: "Unbranded",
    category: "Shoes",
    sizeSystem: "shoe",
    sizeLabel: "UK 9 / EU 43",
    measurements: { "Insole length": '10.8"' },
    condition: "Good",
    conditionNotes: "Uppers polished by us, soles have light wear at the heel.",
    priceCents: 680000,
    salePriceCents: 590000,
    costCents: 150000,
    lot: "BALE-03",
    image: W + "64b1b4f66acab4bf05ce23bc_Sock_Hero.webp",
    images: [],
    description:
      "Brown leather derbies with an open lacing. Creased across the vamp as leather should be, no splits.",
    details: ["Leather upper", "Leather lined", "Rubber heel block"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "canvas-low-tops-uk8",
    sku: "GS-0402",
    name: "Canvas Low Tops",
    tagline: "Scuffed in the right way",
    brand: "Unbranded",
    category: "Shoes",
    sizeSystem: "shoe",
    sizeLabel: "UK 8 / EU 42",
    measurements: { "Insole length": '10.4"' },
    condition: "Fair",
    conditionNotes: "Toe caps yellowed, one lace replaced. Priced accordingly.",
    priceCents: 240000,
    salePriceCents: 190000,
    costCents: 40000,
    lot: "BALE-03",
    image: W + "64b1b4f66acab4bf05ce23bc_Sock_Hero.webp",
    images: [],
    description:
      "Everyday canvas sneakers with plenty of life left. Insoles cleaned and deodorised.",
    details: ["Cotton canvas upper", "Vulcanised rubber sole", "Cleaned insoles"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "brown-leather-belt-34",
    sku: "GS-0501",
    name: "Brown Leather Belt",
    tagline: "Solid brass, real leather",
    brand: "Unbranded",
    category: "Belts",
    sizeSystem: "length",
    sizeLabel: '34"',
    measurements: {
      "Total length": '38"',
      "Fits waist": '32-36"',
      Width: '1.4"',
    },
    condition: "Good",
    conditionNotes: "Holes are clean, no cracking at the fold.",
    priceCents: 180000,
    salePriceCents: null,
    costCents: 30000,
    lot: "BALE-07",
    image: W + "64af1615f68b92e947931fa4_Tote_Bag_Hero.webp",
    images: [],
    description:
      "Full-grain brown belt with a squared brass buckle. Conditioned before listing.",
    details: ["Full-grain leather", "Brass buckle", "Five holes"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "black-woven-belt-36",
    sku: "GS-0502",
    name: "Black Woven Belt",
    tagline: "Stretches to whatever you are",
    brand: "Unbranded",
    category: "Belts",
    sizeSystem: "length",
    sizeLabel: '36"',
    measurements: {
      "Total length": '40"',
      "Fits waist": '30-38"',
      Width: '1.3"',
    },
    condition: "Excellent",
    conditionNotes: null,
    priceCents: 150000,
    salePriceCents: null,
    costCents: 22000,
    lot: "BALE-07",
    image: W + "64af1615f68b92e947931fa4_Tote_Bag_Hero.webp",
    images: [],
    description:
      "Woven elastic belt with a leather tab. No fixed holes, so it sits wherever you need it.",
    details: ["Woven elastic", "Leather tab", "Metal buckle"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
  {
    slug: "wool-flat-cap-one-size",
    sku: "GS-0601",
    name: "Wool Flat Cap",
    tagline: "Grandad, but on purpose",
    brand: "Unbranded",
    category: "Accessories",
    sizeSystem: "one-size",
    sizeLabel: "One size",
    measurements: { Circumference: '23"' },
    condition: "Good",
    conditionNotes: null,
    priceCents: 220000,
    salePriceCents: null,
    costCents: 35000,
    lot: "BALE-06",
    image: W + "64af14fec3628c1a5b8a0fdb_Hat_Hero.webp",
    images: [W + "64b822f79ca862139f10dfa3_White_Hat_Hero.webp"],
    description:
      "Grey wool-blend flat cap with a stitched brim. Lining clean, shape holds.",
    details: ["Wool blend", "Cotton lining", "Stitched brim"],
    status: "available",
    reservedUntil: null,
    soldAt: null,
  },
];

export const HERO_PRODUCTS = [
  {
    alt: "Hard Hat Long Sleeve-T",
    image: "/assets/WEBP/64adce8962f07616f9cf9b0e_Long_Sleeve_Front.webp",
    className: "w-[18%] min-w-[68px] max-w-[140px] -rotate-6",
  },
  {
    alt: "Sticker Pack",
    image: "/assets/WEBP/64b844c556fec6d53fb9dd9c_Stickersheet_Hero.webp",
    className: "w-[14%] min-w-[56px] max-w-[110px] rotate-3",
  },
  {
    alt: "Company Candle",
    image: "/assets/WEBP/64c07b00efaea300a95aa559_Candle_Hero.webp",
    className: "w-[14%] min-w-[56px] max-w-[110px] -rotate-2",
  },
  {
    alt: "Wink Hat — White",
    image: "/assets/WEBP/64b822f79ca862139f10dfa3_White_Hat_Hero.webp",
    className: "w-[16%] min-w-[62px] max-w-[130px] rotate-6",
  },
  {
    alt: "Company Socks",
    image: "/assets/WEBP/64b1b4f66acab4bf05ce23bc_Sock_Hero.webp",
    className: "w-[14%] min-w-[56px] max-w-[110px] -rotate-3",
  },
];

export const LOGO_THEMES = {
  jitter: {
    logo: "/assets/PNG/64b7173cdd6ff3285af61160_Jitter_00000.png",
    width: 1840,
    height: 710,
    bg: "/assets/AVIF/6495fcd53cebe34b7b5a8fe4_Space-pic-3x-edited-3.avif",
  },
  serif: {
    logo: "/assets/PNG/64b7173c6691efd70d893e3f_Serif_00000.png",
    width: 1920,
    height: 700,
    bg: "/assets/AVIF/6495fcd53cebe34b7b5a8fe4_Space-pic-3x-edited-3.avif",
  },
  transparent: {
    logo: "/assets/PNG/64b7173cdd6ff3285af61160_Jitter_00000.png",
    width: 1840,
    height: 710,
    bg: "/assets/PNG/64b7173b28956c9892088f3c_Transparent_00000.png",
  },
};
