export const MOCK_PROMOS = [
  {
    code: "WELCOME10",
    kind: "percent",
    value: 10,
    minSubtotalCents: 0,
    active: true,
    startsAt: null,
    endsAt: null,
    maxRedemptions: null,
    redemptions: 0,
  },
  {
    code: "FREESHIP",
    kind: "free_shipping",
    value: 0,
    minSubtotalCents: 300000,
    active: true,
    startsAt: null,
    endsAt: null,
    maxRedemptions: null,
    redemptions: 0,
  },
  {
    code: "RS500OFF",
    kind: "fixed",
    value: 50000,
    minSubtotalCents: 400000,
    active: true,
    startsAt: null,
    endsAt: null,
    maxRedemptions: 200,
    redemptions: 12,
  },
  {
    code: "EXPIRED",
    kind: "percent",
    value: 25,
    minSubtotalCents: 0,
    active: true,
    startsAt: null,
    endsAt: "2024-12-31T23:59:59.000Z",
    maxRedemptions: null,
    redemptions: 0,
  },
];
